# Generated by Django 5.0.6 on 2025-07-27 17:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
                ('ioc_type', models.CharField(choices=[('ip', 'IP'), ('domain', 'Domain'), ('hash', 'Hash')], max_length=16)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=32, null=True)),
                ('message', models.TextField()),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('matched_ioc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('pattern', models.CharField(max_length=512)),
                ('use_regex', models.BooleanField(default=False)),
                ('threshold', models.PositiveIntegerField(default=5)),
                ('window_seconds', models.PositiveIntegerField(default=300)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_message', models.TextField(blank=True, null=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rule')),
            ],
        ),
    ]
